### ISSUE TITLE
How to inference the wild videos? or test the pre-trained models?

### ISSUE THREAD

**Issue by XianyuFFF** [kkahatapitiya/Coarse-Fine-Networks#1]
Thank you very much for your work.
I want to inference the wild videos. Can you help me with how to inference my own videos? or test the pre-trained models? I only found the training codes.
Thanks

**Comment by kkahatapitiya** [comment]
Currently, we don't have any script to evaluate on custom data. But you can do a few adjustments to test on custom data based on our pre-trained models:
1. Edit the dataset file [charades_fine.py](https://github.com/kkahatapitiya/Coarse-Fine-Networks/blob/main/charades_fine.py) to feed your data and use [extract_fineFEAT.py](https://github.com/kkahatapitiya/Coarse-Fine-Networks/blob/main/extract_fineFEAT.py) to pre-extract fine features for your data.
2. Modify the dataset file [charades_coarse_fineFEAT.py](https://github.com/kkahatapitiya/Coarse-Fine-Networks/blob/main/charades_coarse_fineFEAT.py) as same as you did before, and use [train_coarse_fineFEAT.py](https://github.com/kkahatapitiya/Coarse-Fine-Networks/blob/main/train_coarse_fineFEAT.py) evaluate on your custom data. Currently this script is set to validation mode only ([this line](https://github.com/kkahatapitiya/Coarse-Fine-Networks/blob/515a9361532fced0a139aad5c40b8068534bd466/train_coarse_fineFEAT.py#L162)). It will give you mAP and write predictions to a .csv file.

**Comment by dragen1860** [comment]
@kkahatapitiya would you kindly share some code on given any my own video, simple run your model and output the action curve? thank you very much.
