### ISSUE TITLE
Which tools you used to draw the elegant diagram?

### ISSUE THREAD

**Issue by dragen1860** [kkahatapitiya/Coarse-Fine-Networks#10]
Dear author: 
   thanks for sharing the insightful work! it helps!
   I wonder which tool you used to draw these diagram in your paper:
 
![image](https://user-images.githubusercontent.com/4252555/146319574-81712d9e-909a-423f-b0df-771a89bd6c7d.png)

it looks very vivid. congratulations!

**Comment by kkahatapitiya** [comment]
Thanks so much for your comment. I use https://www.diagrams.net and highly recommend it. Hope it helps!
