### ISSUE TITLE
would you plan to release test code for the model ？

### ISSUE THREAD

**Issue by hiredd** [kkahatapitiya/Coarse-Fine-Networks#2]
how to test a custom video？

**Comment by kkahatapitiya** [comment]
We currently don't have a script to test a custom video. But, if you have a custom dataloader (or you can edit our dataloader to fit your custom data in a few steps) you can use the same training (+validation) scripts to evaluate custom data. Please refer: [https://github.com/kkahatapitiya/Coarse-Fine-Networks/issues/1](https://github.com/kkahatapitiya/Coarse-Fine-Networks/issues/1)

**Comment by hiredd** [comment]
thank you for your reply！
