### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/nfs/bigcornea/add_disk0/kumarak/fine_spatial7x7/layer1/FPJ9D'

### ISSUE THREAD

**Issue by hiredd** [kkahatapitiya/Coarse-Fine-Networks#3]
how to train train_coarse_fineFEAT.py？

**Comment by kkahatapitiya** [comment]
You first need to use `train_fine.py` To pre-extract fine features. It will save features in {layer1, layer2, layer3, layer4, conv5} which will be inputs to `train_coarse_fineFEAT.py`
