### ISSUE TITLE
ModuleNotFoundError: No module named 'videotransforms' and 'loss_utils'

### ISSUE THREAD

**Issue by yiheo** [kkahatapitiya/Coarse-Fine-Networks#4]
Hi
I'm just trying to run this code.
However, I faced to some module error from the first train code,
`python train_fine.py -gpu {gpu_num}`

```
File "train_fine.py", line 22, in <module>
   import videotransforms
ModuleNotFoundError: No module named 'videotransforms'
```
```
File "/workspace/Coarse-Fine-Networks/x3d_fine.py", line 7, in <module>
    import loss_utils
ModuleNotFoundError: No module named 'loss_utils'
```
Would you explain how to solve the error?

**Comment by kkahatapitiya** [comment]
Please feel free to comment these lines, they are not required. Sorry about the confusion.
