### ISSUE TITLE
Hardware requirements to train/test

### ISSUE THREAD

**Issue by InnovArul** [kkahatapitiya/Coarse-Fine-Networks#7]
Could you please mention the hardware setup (number of GPUs and type of GPUs) you used to train/test the models and the time taken to train the models (per epoch)?

Thanks in advance!

**Comment by kkahatapitiya** [comment]
I used 4 Titan RTX (24GB) gpus, and trained in a two-step fashion. To pretrain on Kinetics, it take around 4-5days. As to finetune on Charades, it only takes a couple of hours.

**Comment by InnovArul** [comment]
Thanks for your reply!
