### ISSUE TITLE
Reproduce the numbers you reported

### ISSUE THREAD

**Issue by Lilyo** [kkahatapitiya/Coarse-Fine-Networks#8]
Hi @kkahatapitiya , 

Thank you in advance for your excellent work! 
As you mentioned in your README.md: "use this evaluation script to reproduce our reported numbers."

I want to know where I can get your results (such as this "test_submission_localize.txt", which is required by "Charades_v1_localize.m"), because I want to reproduce the numbers you reported.

I'm looking forward to your reply!

Thanks

**Comment by kkahatapitiya** [comment]
[localize_corr_v1.csv](https://github.com/kkahatapitiya/Coarse-Fine-Networks/blob/main/localize_corr_v1.csv) is the file you are looking for.

**Comment by Lilyo** [comment]
Hi, 

Does this mean I can type the command line below directly in MATLAB?

`[rec_all,prec_all,ap_all,map]=Charades_v1_localize('localize_corr_v1.csv','Charades_v1_test.csv');`

**Comment by kkahatapitiya** [comment]
Yes, I think so. The annotation file should be `Charades_vu17_validation.csv `

**Comment by Lilyo** [comment]
Yes, It solved my problem. Thanks.
